# DocFX Filtering Rules
apiRules:
- include: # The namespaces to generate
    uidRegex: .^JelleVer.Localisation
    type: Namespace
#- exclude:
#    uidRegex: .* # Every other namespaces are ignored
#    type: Namespace